blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/primihub/fedps/discussions/new
    about: Please ask and answer usage questions on Discussions
  - name: Blank issue
    url: https://github.com/primihub/fedps/issues/new
    about: Please note that other templates should be used in most cases